services:
  smartgpt:
    build: .
    working_dir: /smartgpt
    network_mode: host
    # depends_on:
    #   - qdrant
    #   - redis
    ports: 
      - "3001:3001"
    volumes:
      - .:/smartgpt
    # environment:
    #   QDRANT_HOST: ${QDRANT_HOST:-qdrant}
    #   REDIS_HOST: ${REDIS_HOST:-redis}
    entrypoint:
      - /usr/bin/tini
      - --
    command:
      - cargo
      - run
      - --release
  qdrant:
    image: "qdrant/qdrant"
    network_mode: host
    # ports: 
    #   - "6333:6333"
    #   - "6334:6334"
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
    # network_mode: host